name: CI

on: [push]

jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
    - name: Sync
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        
    - name: Configure
      shell: pwsh
      run: cmake -S . -B build
      
    - name: Build Debug
      shell: pwsh
      run: cmake --build build --config Debug
      
    - name: Upload Debug artifacts
      uses: actions/upload-artifact@v4
      with:
        name: D3d12info - Debug
        path: ./build/Debug/
      
    - name: Build Release
      shell: pwsh
      run: cmake --build build --config Release
      
    - name: Upload Release artifacts
      uses: actions/upload-artifact@v4
      with:
        name: D3d12info - Release
        path: |
          ./build/Release/
          ! ./build/Release/*.lib
          ! ./build/Release/*.exp
